run:
  gofmt:
    path-prefix: ""
  govet:
    path-prefix: ""
  errcheck:
    path-prefix: ""
  staticcheck:
    path-prefix: ""
  gosimple:
    path-prefix: ""
  ineffassign:
    path-prefix: ""
  unconvert:
    path-prefix: ""
  misspell:
    path-prefix: ""
    locale: US
  gocritic:
    path-prefix: ""
issues:
  exclude-rules:
    # Allow generated files to be excluded from certain linters
    - path: '_test\.go$'
      linters:
        - errcheck
    - path: 'zz_generated'
      linters:
        - all
linters-settings:
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - appendAssign
      - evalOrder
