package cmd

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"
)

// GenerateDocs generates CLI reference Markdown documentation to the given directory.
// Each command gets its own file (e.g., akswitch_start.md, akswitch_stop.md).
// This is used by tools/gen-cli-docs to keep docs/cli/ in sync with the code.
func GenerateDocs(dir string) error {
	// Generate markdown tree
	if err := doc.GenMarkdownTree(rootCmd, dir); err != nil {
		return err
	}

	// Post-process: strip the auto-generated footer line to avoid timestamp diffs
	return filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}

		// Read all lines
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		var lines []string
		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			// Skip the auto-generated footer line
			if strings.Contains(line, "Auto generated by spf13/cobra") {
				continue
			}
			lines = append(lines, line)
		}
		f.Close()
		if err := scanner.Err(); err != nil {
			return err
		}

		// Write back without the footer
		return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0644)
	})
}