package config

import (
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"time"
)

// ProviderRuntimeState is a subset of ProviderState methods needed for runtime config.
// Defined here to avoid importing internal/server (would create circular dependency).
// ProviderState (in internal/server) satisfies this interface structurally.
type ProviderRuntimeState interface {
	SetCooldownSec(v int)
	SetBackoffCapSec(v int)
	SetBackoffMultiplier(v float64)
	SetMaxRetries(v int)
	SetHTTPTimeoutSec(v int)
	SetProxyTimeout(d time.Duration)
	SetUpstreamCBResetTimeout(sec int)
	SetCBResetSec(v int)
	SetUpstreamProxyCBThreshold(n int)
	SetUpstreamCBThreshold(n int)
	SetLogLevel(v string)
	SetThinkingMode(v string)
	SetRectifyThinkingMapTo(v string)
	ConfigurePoolCBs(base, backoffCap time.Duration, multiplier float64)

	CooldownSec() int
	BackoffCapSec() int
	BackoffMultiplier() float64
}

// FieldScope identifies whether a field belongs to a provider or is global.
type FieldScope string

const (
	FieldScopeProvider FieldScope = "provider"
	FieldScopeGlobal   FieldScope = "global"
)

// FieldType is the value type of a config field.
type FieldType string

const (
	FieldTypeInt     FieldType = "int"
	FieldTypeString  FieldType = "string"
	FieldTypeBool    FieldType = "bool"
	FieldTypeFloat64 FieldType = "float64"
)

// ConfigFieldDescriptor describes one configurable field.
type ConfigFieldDescriptor struct {
	Key             string
	DisplayName     string
	Scope           FieldScope
	TomlPath        string // "field" for global, "provider.%s.field" for provider
	Type            FieldType
	Default         string // string representation of default value
	RuntimeEditable bool
	ReadOnly        bool // true = cannot be set via config set (needs TOML edit + reload)
	MinInt          int  // minimum value for int fields; -1 = use default (-1), 0+ = enforce this minimum

	// Parse converts a string value to the field's type. Returns error on invalid input.
	Parse func(string) (any, error)

	// Format converts a typed value back to string for display.
	Format func(any) string

	// Persist writes the parsed value into the Config struct. Provider is the
	// target provider name; for global fields, provider is empty and c is nil.
	Persist func(tc *TomlConfig, provider string, c *Config, value any)

	// ApplyRuntime applies a validated value to ProviderState at runtime.
	// Called by the admin API runtime config endpoint.
	// Provider is the target provider name; ps is the target ProviderState (passed as any).
	// Nil for non-runtime-editable fields.
	ApplyRuntime func(ps any, provider string, value any) (any, error)
}

// IsValidLogLevel reports whether level is a recognized log level.
// Valid levels: debug, info, warn, error.
func IsValidLogLevel(level string) bool {
	switch level {
	case "debug", "info", "warn", "error":
		return true
	}
	return false
}

// ConfigFieldDescriptors is the single source of truth for all configurable fields.
// Provider-scoped fields come first, then global fields.
// Generated by reflection from struct field tags + customClosures overlay.
var ConfigFieldDescriptors = buildDescriptors()

// FindField returns the descriptor for the given key, or nil if not found.
func FindField(key string) *ConfigFieldDescriptor {
	for i := range ConfigFieldDescriptors {
		if ConfigFieldDescriptors[i].Key == key {
			return &ConfigFieldDescriptors[i]
		}
	}
	return nil
}

// ParseDefault converts the Default string to the field's type.
// 保留导出签名（CLI 侧调用），内部委托 parseByType 消除重复。
func ParseDefault(d *ConfigFieldDescriptor) (any, error) {
	return parseByType(d.Type, d.Default)
}

// fieldTag 解析后的 field struct tag。
type fieldTag struct {
	key             string
	display         string
	scope           FieldScope
	defaultOverride string // 空表示未设
	runtime         bool
	readOnly        bool
	min             int // 0 = 未设（与 ConfigFieldDescriptor.MinInt 的 Go 零值一致）
}

// parseFieldTag 解析 `field:"key,display:...,scope:...,default:...,runtime,readonly,min:N"` tag。
func parseFieldTag(tag string) (fieldTag, bool) {
	if tag == "" {
		return fieldTag{}, false
	}
	ft := fieldTag{min: 0} // 0 = 未设（与 ConfigFieldDescriptor.MinInt 的 Go 零值一致）
	parts := strings.Split(tag, ",")
	if parts[0] == "" {
		return fieldTag{}, false
	}
	ft.key = parts[0]
	for _, p := range parts[1:] {
		k, v, _ := strings.Cut(p, ":")
		switch k {
		case "display":
			ft.display = v
		case "scope":
			ft.scope = FieldScope(v)
		case "default":
			ft.defaultOverride = v
		case "runtime":
			ft.runtime = true
		case "readonly":
			ft.readOnly = true
		case "min":
			if n, err := strconv.Atoi(v); err == nil {
				ft.min = n
			}
		}
	}
	return ft, true
}

// reflectTypeField 映射 reflect.Kind → FieldType。
func reflectTypeField(k reflect.Kind) FieldType {
	switch k {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return FieldTypeInt
	case reflect.String:
		return FieldTypeString
	case reflect.Bool:
		return FieldTypeBool
	case reflect.Float32, reflect.Float64:
		return FieldTypeFloat64
	default:
		return FieldTypeString // 兜底，不应出现
	}
}

// zeroDefault 返回类型零值的字符串表示。
func zeroDefault(t FieldType) string {
	switch t {
	case FieldTypeInt:
		return "0"
	case FieldTypeFloat64:
		return "0"
	case FieldTypeBool:
		return "false"
	default:
		return ""
	}
}

// parseByType 是由 Type 决定的默认 Parse。
func parseByType(t FieldType, s string) (any, error) {
	switch t {
	case FieldTypeInt:
		return strconv.Atoi(s)
	case FieldTypeFloat64:
		return strconv.ParseFloat(s, 64)
	case FieldTypeBool:
		return strconv.ParseBool(s)
	case FieldTypeString:
		return s, nil
	default:
		return nil, fmt.Errorf("unknown field type: %s", t)
	}
}

// formatByType 是由 Type 决定的默认 Format。
func formatByType(t FieldType, v any) string {
	switch t {
	case FieldTypeInt:
		return strconv.Itoa(v.(int))
	case FieldTypeFloat64:
		f := v.(float64)
		if f == float64(int64(f)) {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', 1, 64)
	case FieldTypeBool:
		return strconv.FormatBool(v.(bool))
	case FieldTypeString:
		return fmt.Sprintf("%v", v)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makePersist 为 provider/global scope 构造派生 Persist 闭包。
// structFieldName 是 Go struct 字段名（如 "CooldownSec"），用于反射定位。
func makePersist(structFieldName string, scope FieldScope) func(tc *TomlConfig, provider string, c *Config, value any) {
	return func(tc *TomlConfig, provider string, c *Config, value any) {
		if scope == FieldScopeProvider {
			if c == nil {
				return
			}
			reflect.ValueOf(c).Elem().FieldByName(structFieldName).Set(reflect.ValueOf(value))
			return
		}
		if tc == nil {
			return
		}
		reflect.ValueOf(tc).Elem().FieldByName(structFieldName).Set(reflect.ValueOf(value))
	}
}

// scanStruct 反射扫描一个 struct 的 field tag，生成基础 descriptor。
// 传入 reflect.TypeOf(&ProviderConfig{}) 之类的指针类型。
func scanStruct(typ reflect.Type, defaultScope FieldScope) []ConfigFieldDescriptor {
	var out []ConfigFieldDescriptor
	t := typ.Elem()
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		ft, ok := parseFieldTag(sf.Tag.Get("field"))
		if !ok {
			continue // 无 field tag，跳过
		}
		scope := ft.scope
		if scope == "" {
			scope = defaultScope
		}
		fType := reflectTypeField(sf.Type.Kind())
		tomlName := sf.Tag.Get("toml")
		// toml tag 可能带 ",omitempty"，取逗号前部分
		if c := strings.Index(tomlName, ","); c >= 0 {
			tomlName = tomlName[:c]
		}
		var tomlPath string
		if scope == FieldScopeProvider {
			tomlPath = "provider.%s." + tomlName
		} else {
			tomlPath = tomlName
		}
		// Default 派生：field tag defaultOverride > default struct tag > 类型零值
		def := ft.defaultOverride
		if def == "" {
			def = sf.Tag.Get("default")
		}
		if def == "" {
			def = zeroDefault(fType)
		}
		d := ConfigFieldDescriptor{
			Key:             ft.key,
			DisplayName:     ft.display,
			Scope:           scope,
			TomlPath:        tomlPath,
			Type:            fType,
			Default:         def,
			RuntimeEditable: ft.runtime,
			ReadOnly:        ft.readOnly,
			MinInt:          ft.min,
			Parse:           func(s string) (any, error) { return parseByType(fType, s) },
			Format:          func(v any) string { return formatByType(fType, v) },
			Persist:         makePersist(sf.Name, scope),
		}
		out = append(out, d)
	}
	return out
}

// customClosure 存放无法反射派生的定制闭包。任一字段为 nil 表示用派生默认。
type customClosure struct {
	Parse        func(string) (any, error)
	Format       func(any) string
	ApplyRuntime func(ps any, provider string, value any) (any, error)
}

// customClosures 按 field key 索引定制闭包（无法反射派生的 Parse/Format/ApplyRuntime）。
var customClosures = map[string]customClosure{
	"cooldown_sec": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 1 {
				return nil, fmt.Errorf("cooldown_sec must be a positive integer")
			}
			ps.(ProviderRuntimeState).SetCooldownSec(v)
			ps.(ProviderRuntimeState).ConfigurePoolCBs(
				time.Duration(v)*time.Second,
				time.Duration(ps.(ProviderRuntimeState).BackoffCapSec())*time.Second,
				ps.(ProviderRuntimeState).BackoffMultiplier(),
			)
			return v, nil
		},
	},
	"max_retries": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 0 {
				return nil, fmt.Errorf("max_retries must be a non-negative integer")
			}
			ps.(ProviderRuntimeState).SetMaxRetries(v)
			return v, nil
		},
	},
	"backoff_cap_sec": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 1 {
				return nil, fmt.Errorf("backoff_cap_sec must be a positive integer")
			}
			ps.(ProviderRuntimeState).SetBackoffCapSec(v)
			ps.(ProviderRuntimeState).ConfigurePoolCBs(
				time.Duration(ps.(ProviderRuntimeState).CooldownSec())*time.Second,
				time.Duration(v)*time.Second,
				ps.(ProviderRuntimeState).BackoffMultiplier(),
			)
			return v, nil
		},
	},
	"backoff_multiplier": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.ParseFloat(value.(string), 64)
			if err != nil || v < 1.0 {
				return nil, fmt.Errorf("backoff_multiplier must be a number >= 1.0")
			}
			ps.(ProviderRuntimeState).SetBackoffMultiplier(v)
			ps.(ProviderRuntimeState).ConfigurePoolCBs(
				time.Duration(ps.(ProviderRuntimeState).CooldownSec())*time.Second,
				time.Duration(ps.(ProviderRuntimeState).BackoffCapSec())*time.Second,
				v,
			)
			return v, nil
		},
	},
	"cb_reset_sec": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 1 {
				return nil, fmt.Errorf("cb_reset_sec must be a positive integer")
			}
			ps.(ProviderRuntimeState).SetUpstreamCBResetTimeout(v)
			ps.(ProviderRuntimeState).SetCBResetSec(v)
			return v, nil
		},
	},
	"upstream_cb_threshold": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 1 {
				return nil, fmt.Errorf("upstream_cb_threshold must be a positive integer")
			}
			ps.(ProviderRuntimeState).SetUpstreamProxyCBThreshold(v)
			ps.(ProviderRuntimeState).SetUpstreamCBThreshold(v)
			return v, nil
		},
	},
	"http_timeout_sec": {
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			v, err := strconv.Atoi(value.(string))
			if err != nil || v < 1 {
				return nil, fmt.Errorf("http_timeout_sec must be a positive integer")
			}
			ps.(ProviderRuntimeState).SetProxyTimeout(time.Duration(v) * time.Second)
			ps.(ProviderRuntimeState).SetHTTPTimeoutSec(v)
			return v, nil
		},
	},
	"log_level": {
		Parse: func(s string) (any, error) {
			v := strings.TrimSpace(strings.ToLower(s))
			if !IsValidLogLevel(v) {
				return nil, fmt.Errorf("invalid log level %q, use: debug, info, warn, error", s)
			}
			return v, nil
		},
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			s, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("log_level must be a string")
			}
			v := strings.TrimSpace(strings.ToLower(s))
			if !IsValidLogLevel(v) {
				return nil, fmt.Errorf("invalid log level, use: debug, info, warn, error")
			}
			ps.(ProviderRuntimeState).SetLogLevel(v)
			return v, nil
		},
	},
	"thinking_mode": {
		Parse: func(s string) (any, error) {
			v := strings.TrimSpace(strings.ToLower(s))
			switch v {
			case "default", "rectify":
				return v, nil
			}
			return nil, fmt.Errorf("invalid thinking_mode %q, use: default, rectify", s)
		},
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			s, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("thinking_mode must be a string")
			}
			v := strings.TrimSpace(strings.ToLower(s))
			switch v {
			case "default", "rectify":
				ps.(ProviderRuntimeState).SetThinkingMode(v)
				return v, nil
			default:
				return nil, fmt.Errorf("invalid thinking_mode %q, use: default, rectify", s)
			}
		},
	},
	"rectify_thinking_map_to": {
		Parse: func(s string) (any, error) {
			v := strings.TrimSpace(strings.ToLower(s))
			switch v {
			case "enabled", "auto", "disabled":
				if v == "disabled" {
					v = ""
				}
				return v, nil
			}
			return nil, fmt.Errorf("invalid rectify_thinking_map_to %q, use: enabled, auto, disabled", s)
		},
		Format: func(v any) string {
			s := v.(string)
			if s == "" {
				return "disabled"
			}
			return s
		},
		ApplyRuntime: func(ps any, provider string, value any) (any, error) {
			s, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("rectify_thinking_map_to must be a string")
			}
			v := strings.TrimSpace(strings.ToLower(s))
			switch v {
			case "enabled", "auto", "disabled":
				if v == "disabled" {
					v = ""
				}
				ps.(ProviderRuntimeState).SetRectifyThinkingMapTo(v)
				return v, nil
			default:
				return nil, fmt.Errorf("invalid rectify_thinking_map_to %q, use: enabled, auto, disabled", s)
			}
		},
	},
	"key_selection": {
		Parse: func(s string) (any, error) {
			v := strings.TrimSpace(strings.ToLower(s))
			switch v {
			case "polling", "random":
				return v, nil
			}
			return nil, fmt.Errorf("invalid key_selection %q, use: polling, random", s)
		},
	},
}

// reflectBuildDescriptors 遍历 ProviderConfig + TomlConfig 的 field tag，
// 反射生成所有字段的基础 descriptor（含派生 Parse/Format/Persist，无 ApplyRuntime）。
func reflectBuildDescriptors() []ConfigFieldDescriptor {
	out := scanStruct(reflect.TypeOf(&ProviderConfig{}), FieldScopeProvider)
	out = append(out, scanStruct(reflect.TypeOf(&TomlConfig{}), FieldScopeGlobal)...)
	return out
}

// buildDescriptors 组装最终 descriptor：反射基础 + customClosures overlay。
func buildDescriptors() []ConfigFieldDescriptor {
	base := reflectBuildDescriptors()
	for i := range base {
		if cc, ok := customClosures[base[i].Key]; ok {
			if cc.Parse != nil {
				base[i].Parse = cc.Parse
			}
			if cc.Format != nil {
				base[i].Format = cc.Format
			}
			if cc.ApplyRuntime != nil {
				base[i].ApplyRuntime = cc.ApplyRuntime
			}
		}
	}
	return base
}
